spring.application.name=AnalisisFinanciero-back
server.port=8080

#Configuración DataBase
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_citassalud
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.media-types.json=application/json

# Habilitar/deshabilitar api-docs -swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html

# IMPORTANTE: Usa la URL publica completa SOLO si accedes desde Codespaces
swagger.server.url=http://localhost:8080/api

# Configuracion JWT
jwt.secret=0wF9Au1Y3vNcLdTJDwsZZDuGZsjuBQwTXh3qrG62hsSxJDIeD7
jwt.expirationMs=28800000

