
# Configuración básica para entorno productivo usando variables de entorno
spring.application.name=${APP_NAME:AnalisisFinanciero-back}
server.port=${SERVER_PORT:8080}
server.servlet.context-path=${CONTEXT_PATH:/api}

# Base de datos PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html

# JWT
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION:86400000}

# Actuadores de Spring Boot
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

